version: "3.2"
services:
  db:
    image: mdillon/postgis:10
    environment:
      POSTGRES_DB: public_comment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    networks:
      - main
  redis:
    image: redis
    networks:
      - main
    ports:
      - 6379:6379
  s3:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    networks:
      - main
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        pipenv_arg: --dev
    environment:
      - DJANGO_SETTINGS_MODULE=public_comment.settings.local
      - DJANGO_REQUEST_LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      - REDISCLOUD_URL=redis://redis:6379/0
      - USE_STAGING_REGULATIONS_API=${USE_STAGING_REGULATIONS_API:-True}
    volumes:
      - ./public_comment:/app
    networks:
      - main
    depends_on:
      - db
      - redis
      - s3
    ports:
      - 80:80
  celery:
    stdin_open: true
    tty: true
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=public_comment.settings.local
      - DJANGO_REQUEST_LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      - REDISCLOUD_URL=redis://redis:6379/0
      - COLUMNS=80
      - USE_STAGING_REGULATIONS_API=${USE_STAGING_REGULATIONS_API:-True}
    volumes:
      - ./public_comment:/app
    networks:
      - main
    depends_on:
      - db
      - redis
    command: /app/manage.py celery_worker

networks:
  main: